### ISSUE TITLE
ResCons can't import clustalo_embl_api

### ISSUE THREAD

**Issue by xihh87** [ManavalanG/ResCons#1]
On ubuntu 16.04 using Python 2.7.12 `(default, Nov 19 2016, 06:48:10)`,
and dependencies installed on a virtualenv:

- biopython
- clustalo
- xmltramp2

As stated in the README, file ResCons.py was copied to `bin` directory and `Rescons_Files` was copied to `lib/python2.7/site-packages/`.

When trying to run `ResCons.py` I get the following error:

```
Traceback (most recent call last):
  File "ResCons.py", line 65, in <module>
    from ResCons_Files.clustalo_embl_api import clustalo_api            # to run clustal omega through EMBL webserver
ImportError: No module named ResCons_Files.clustalo_embl_api
```

Any pointers to solve this error?

**Comment by ManavalanG** [comment]
Problem is that script `ResCons.py` and directory `ResCons_Files` are stored in different locations. Copy them both in the same directory and run the script. 

Example directory structure:
`dir_X`
`             |_ Rescons.py`
`             |_ResCons_Files`

Refer to [user guide](https://github.com/ManavalanG/ResCons/blob/master/User_Guide_ResCons.pdf) for further instructions.

**Comment by xihh87** [comment]
I've tried as recommended. However I get the same error.

```
~/venvs/rescons$ tree
.
├── Rescons_Files
│   ├── 128no_bg_logo.gif
│   ├── 128x128_no_bg_logo.png
│   ├── 128x128_part_no_bg_logo.ico
│   ├── 128x128_part_no_bg_logo.png
│   ├── 64x64_part_no_bg_logo.ico
│   ├── clustalo_embl_api.py
│   ├── clustalo_embl_api.pyc
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── ResCons_windows_logo.ico
│   ├── Settings_ResCons.txt
│   ├── Similarity_Matrix_S_Original.txt
│   ├── Similarity_Matrix_S.txt
│   ├── Template_html5_chartjs.txt
│   └── Template_html5_ChartNewjs.txt
└── ResCons.py

1 directory, 17 files
~/venvs/rescons$ ./ResCons.py
Traceback (most recent call last):
  File "./ResCons.py", line 65, in <module>
    from ResCons_Files.clustalo_embl_api import clustalo_api            # to run clustal omega through EMBL webserver
ImportError: No module named ResCons_Files.clustalo_embl_api
```

**Comment by ManavalanG** [comment]
I see the error now. Directory `Rescons_Files` needs to be renamed to `ResCons_Files` (ie. case change of letter c). I'll update the code soon to reflect this error-fix. Thanks for bringing it up.

**Comment by ManavalanG** [comment]
Note to self: Turns out this problem (wrong case of letter C in dirname `ResCons_Files` ) was raised due to Git's handling of case-sensitivity. Used [this solution](https://stackoverflow.com/a/11183844/3998252) to fix this issue.
